"""empty message

Revision ID: e80146b5e9d0
Revises: a562f232e2f9
Create Date: 2021-11-30 21:02:46.667559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e80146b5e9d0'
down_revision = 'a562f232e2f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth0_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'auth0_id')
    # ### end Alembic commands ###
